#!/usr/bin/env ruby
# encoding: UTF-8
# Generates Limor Ai App/BuildInfo.swift with the current git SHA each
# build, so the Settings → version footer can show the actual commit.
#
# Why not just patch Info.plist?
#
# The old version of this tool added a build phase *after* Sources +
# Resources that wrote LIMOR_GIT_SHA into the bundled Info.plist via
# PlistBuddy. That looked like it worked — `[inject-git-sha]` printed
# the SHA, the file existed — but the build was wiping us silently:
# Xcode's standard `ProcessInfoPlistFile` step runs later in the build
# and regenerates the bundled plist from the source plist, with no
# memory of our injected key. The user ended up with "dev" forever.
#
# Trying to fix it via Xcode's build-graph (input_paths / output_paths
# pointing at `${BUILT_PRODUCTS_DIR}/${INFOPLIST_PATH}`) hit either a
# "mutable output but no other virtual output node" rejection or a
# build cycle, because ProcessInfoPlistFile owns that file and Xcode
# refuses to let anyone else claim it.
#
# Generating a Swift source file sidesteps the whole problem: the
# script runs BEFORE the Sources build phase, writes a plain Swift
# enum into the source tree, and the normal compile pipeline turns
# it into a constant the app reads at runtime. No plist racing, no
# build cycles.

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

require "xcodeproj"

PROJECT_PATH = File.expand_path(File.join(__dir__, "..", "Limor Ai App.xcodeproj"))
TARGET_NAME = "Limor Ai App"
PHASE_NAME = "Inject Git SHA"

SHELL_SCRIPT = <<~SHELL
  # Regenerate BuildInfo.swift with the current git short SHA so the
  # Settings footer reflects what the user is actually running. We
  # write a plain Swift enum that the Sources phase (scheduled after
  # this one) compiles in. Failures fall back to "dev" and emit a
  # `warning:` line so the build log explains why if anything trips.

  GIT_BIN=$(command -v git || true)
  if [ -z "$GIT_BIN" ] && [ -x /usr/bin/git ]; then
    GIT_BIN=/usr/bin/git
  fi

  if [ -z "$GIT_BIN" ]; then
    echo "warning: [inject-git-sha] git not found on PATH; falling back to 'dev'"
    GIT_SHA="dev"
  else
    GIT_OUT=$("$GIT_BIN" -C "${SRCROOT}" rev-parse --short HEAD 2>&1)
    GIT_RC=$?
    if [ $GIT_RC -ne 0 ]; then
      echo "warning: [inject-git-sha] git rev-parse failed (rc=$GIT_RC) at ${SRCROOT}: $GIT_OUT"
      GIT_SHA="dev"
    else
      GIT_SHA="$GIT_OUT"
    fi
  fi

  OUT="${SRCROOT}/Limor Ai App/BuildInfo.swift"
  mkdir -p "$(dirname "$OUT")"
  cat > "$OUT" <<EOF
  // Auto-generated by tools/inject-git-sha.rb on every build.
  // Do not edit by hand; do not commit changes — see .gitignore.
  enum BuildInfo {
      static let gitSha: String = "$GIT_SHA"
  }
  EOF

  echo "[inject-git-sha] BuildInfo.gitSha=\\"$GIT_SHA\\" → $OUT"
  exit 0
SHELL

project = Xcodeproj::Project.open(PROJECT_PATH)
target = project.targets.find { |t| t.name == TARGET_NAME }
abort "target '#{TARGET_NAME}' not found" unless target

existing = target.build_phases.find do |phase|
  phase.respond_to?(:name) && phase.name == PHASE_NAME
end

phase = existing || target.new_shell_script_build_phase(PHASE_NAME)
phase.shell_script = SHELL_SCRIPT

# The script writes BuildInfo.swift, which Sources then compiles —
# so we MUST run before Sources. Move us to position 0 of the build
# phases list. Idempotent if we're already there.
sources_phase = target.source_build_phase
phases = target.build_phases
unless phases.first == phase
  phases.delete(phase)
  phases.unshift(phase)
end

# Empty input/output paths — we deliberately want "always re-run"
# semantics. The cost is one extra `cat` per build (negligible) and
# we never miss a SHA refresh after a commit. The plist approach used
# to declare these too, but that's what caused the build cycle with
# ProcessInfoPlistFile.
phase.input_paths = []
phase.output_paths = []

puts existing ? "[inject-git-sha] updated existing build phase" : "[inject-git-sha] added new build phase"

target.build_configurations.each do |config|
  # Xcode 15+ sandboxes Run Script phases by default, which blocks
  # `git rev-parse` against the project SRCROOT. Sandbox off only on
  # this target — we're running locally-known commands (git + cat)
  # against project-local paths, nothing that needs the extra
  # protection.
  config.build_settings["ENABLE_USER_SCRIPT_SANDBOXING"] = "NO"
end

project.save
puts "[inject-git-sha] saved project"
